p8105_hw2_rmk2196.Rmd
================
2026-10-06

## Problem 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)

transit_df =
  read_csv(
    "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")
  ) |>
  janitor::clean_names() |>
  select(
    line, station_name, station_latitude, station_longitude,
    starts_with("route"), entry, vending, entrance_type, ada
  ) |>
  mutate(entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE))
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

The data is not tidy.

``` r
transit_df |> distinct(line, station_name) |> nrow()
```

    ## [1] 465

``` r
transit_df |> filter(ada == TRUE) |> distinct(line, station_name) |> nrow()
```

    ## [1] 84

``` r
transit_df |> filter(vending == "NO") |> pull(entry) |> mean()
```

    ## [1] 0.3770492

1.  There are 465 distinct stations
2.  There are 84 stations that are ADA compliant
3.  0.3770492 is the proportion of station entrances/exits without
    vending allow entrance

## Reformat data

``` r
transit_tidy =
  transit_df |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name"
  ) |>
  drop_na(route_name)

transit_tidy |> filter(route_name == "A") |> distinct(line, station_name) |> nrow()
```

    ## [1] 60

``` r
transit_tidy |> filter(route_name == "A", ada == TRUE) |> distinct(line, station_name) |> nrow()
```

    ## [1] 17

60 stations serve the A train, and 17 of them are ADA compliant

## Problem 2

``` r
trash_path = "data/202610 Trash Wheel Collection Data.xlsx"

mr_trash =
  read_excel(trash_path, sheet = "Mr. Trash Wheel", range = cell_cols("A:N")) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    year = as.numeric(year),
    trash_wheel = "Mr. Trash Wheel"
  )

prof_trash =
  read_excel(
    trash_path, sheet = "Professor Trash Wheel",
    range = cell_cols("A:M"), na = c("", "dive")
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(trash_wheel = "Professor Trash Wheel")

gwynnda =
  read_excel(
    trash_path, sheet = "Gwynnda the Good Wheel of the W",
    range = cell_cols("A:L")
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(trash_wheel = "Gwynnda")

trash_df = bind_rows(mr_trash, prof_trash, gwynnda) |> relocate(trash_wheel)
```

The dataset has 1269 observations and 15 variables and each row is one
dumpster filled by one of three trash wheels, which are Mr. Trash Wheel
(740 dumpsters), Professor Trash Wheel (137), and Gwynnda (392). Key
variables include `trash_wheel`, which identifies the wheel; `dumpster`,
`date`, `month`, and `year`, which identify when each dumpster was
collected; `weight_tons` and `volume_cubic_yards`, which measure how
much trash it held; and counts of specific items such as
`plastic_bottles`, `cigarette_butts`, and `wrappers`. `homes_powered`
estimates how many homes could be powered by the electricity generated
from the trash. Not every wheel records every item: `sports_balls` is
only recorded for Mr. Trash Wheel, and `glass_bottles` is not recorded
for Gwynnda, so these are missing for the other wheels. For the
available data, Professor Trash Wheel collected a total of 294.96 tons
of trash, and Gwynnda collected 18,120 cigarette butts in June 2022.

``` r
baseline_raw =
  read_csv("data/MCI_baseline.csv", skip = 1, na = c(".", "NA", "")) |>
  janitor::clean_names() |>
  mutate(
    sex = case_match(sex, 1 ~ "male", 0 ~ "female"),
    apoe4 = case_match(apoe4, 1 ~ "carrier", 0 ~ "non-carrier")
  )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
baseline_df =
  baseline_raw |>
  filter(is.na(age_at_onset) | age_at_onset > current_age)
```

``` r
nrow(baseline_raw)                                   # recruited
```

    ## [1] 483

``` r
nrow(baseline_df)                                    # met inclusion criteria
```

    ## [1] 479

``` r
baseline_df |> drop_na(age_at_onset) |> nrow()       # developed MCI
```

    ## [1] 93

``` r
baseline_df |> pull(current_age) |> mean()           # average baseline age
```

    ## [1] 65.0286

``` r
baseline_df |> filter(sex == "female") |> pull(apoe4) |> (\(x) mean(x == "carrier"))()
```

    ## [1] 0.3

``` r
amyloid_df =
  read_csv("data/mci_amyloid.csv", skip = 1, na = c("NA", "Na", "")) |>
  janitor::clean_names() |>
  rename(id = study_id) |>
  pivot_longer(
    baseline:time_8,
    names_to = "time",
    values_to = "amyloid_ratio"
  ) |>
  mutate(amyloid_ratio = as.numeric(amyloid_ratio))
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
anti_join(baseline_df, amyloid_df, by = "id") |> distinct(id) |> nrow()  # baseline only
```

    ## [1] 8

``` r
anti_join(amyloid_df, baseline_df, by = "id") |> distinct(id) |> nrow()  # amyloid only
```

    ## [1] 16

``` r
mci_df = inner_join(baseline_df, amyloid_df, by = "id")

write_csv(mci_df, "data/mci_combined.csv")
```
